=encoding utf8

=head1 ABOUT

This is a source repository to reproduce a bug with the node.js debugger. It
was verified to be present with node-v5.4.0 built from source on Mageia Linux
x86 v6 (Cauldron).

To reproduce run something like:

    ~/apps/node-js/bin/node debug perlito5.js -I src5/lib -I MyDir/lib -I MyDir/lib/expand-solitaire-multi-card-moves

There is a C<RUN_ME.bash> there for that for your convenience.

The debugger starts, type “c” once and get a prompt back (why?) and press “c”
again and the debugger gets stuck and cannot be exited with either Ctrl+C
or Ctrl+Z.

=head1 LICENSE

This code is derived from code from these sources:

=over 4

=item * Perlito

See L<https://github.com/fglock/Perlito> I used commit
b586f8f98d47e8d3d31439fd019777fa6ee12b7d

=item * fc-solve’s Games-Solitaire-Verify

See
L<https://github.com/shlomif/fc-solve/tree/master/cpan/Games-Solitaire-Verify>

=back

B<NOTE!> This code is a compiler for Perl 5, but is not dependent on perl 5
itself.

=cut

